#Copyright 2019 OPNFV and Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Remove bar-zookeeper container
  docker_container:
    name: bar-zookeeper
    state: absent
  tags:
    - remove_containers
    - remove_bar-zookeeper
  when: rm_containers|default(false)|bool == true

- name: Remove zookeeper image
  docker_image:
    state: absent
    name: zookeeper:3.4.11
  tags:
    - remove_images
    - remove_zookeeper_image
  when: rm_images|default(false)|bool == true

- name: launch zookeeper container
  docker_container:
    name: bar-zookeeper
    image: zookeeper:3.4.11
    detach: yes
    state: started
    restart: yes
    network_mode: host
