# Copyright 2021 Xoriant Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3'
services:
  smo-influxdb:
        container_name: smo-influxdb
        image: influxdb:1.8.5
        ports:
             - 8086:8086
        networks:
             - smo-net
        environment:
             INFLUXDB_DATA_MAX_SERIES_PER_DATABASE: 0
             INFLUXDB_DATA_MAX_VALUES_PER_TAG: 0
  smo-grafana:
        container_name: smo-grafana
        image: grafana/grafana:7.5.11
        ports:
             - 3000:3000
        networks:
             - smo-net
        depends_on:
             - smo-influxdb
             - smo-influxdb-connector
  smo-zookeeper:
        container_name: smo-zookeeper
        image: confluentinc/cp-zookeeper:5.5.6
        networks:
             - smo-net
        environment:
             ZOOKEEPER_CLIENT_PORT: 22181
             ZOOKEEPER_TICK_TIME: 2000
  smo-kafka:
         container_name: smo-kafka
         image: confluentinc/cp-kafka:5.5.6
         networks:
             - smo-net
         depends_on:
             - smo-zookeeper
         ports:
             - 29092:29092
         environment:
              KAFKA_BROKER_ID: 2
              KAFKA_ZOOKEEPER_CONNECT: smo-zookeeper:22181
              KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://smo-kafka:29092,PLAINTEXT_HOST://localhost:39092
              KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
              KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
              KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  smo-kafdrop:
         container_name: smo-kafdrop
         image: obsidiandynamics/kafdrop:3.27.0
         networks:
             - smo-net
         depends_on:
             - smo-kafka
         ports:
             - 29000:9000
         environment:
                 KAFKA_BROKERCONNECT: smo-kafka:29092
  smo-dmaap-adapter:
         container_name: smo-dmaap-adapter
         image: nexus3.o-ran-sc.org:10004/smo-dmaap-adapter:5.0.1
         networks:
             - smo-net
         ports:
             - 5000:5000
         environment:
             kafka_host: "smo-kafka"
             kafka_port: "29092"
             log_level: "DEBUG"
             enable_assert: "False"
  smo-collector:
         container_name: smo-collector
         image: nexus3.o-ran-sc.org:10004/smo-collector:5.0.1
         networks:
             - smo-net
         ports:
             - 9999:9999
         volumes:
             - ~/ves-certificate:/opt/smo/certs
         environment:
                 smo_kafka_host: "smo-kafka"
                 smo_kafka_port: "29092"
                 smo_kafka_topic: "smo-events"
                 collector_host: "smo-collector"
                 collector_port: "9999"
                 collector_user: "user"
                 collector_pass: "password"
                 collector_path: ""
                 loglevel: "ERROR"
                 enable_assert: "False"
         depends_on:
             - smo-kafka
  smo-influxdb-connector:
         container_name: smo-influxdb-connector
         image: nexus3.o-ran-sc.org:10004/smo-influxdb-connector:5.0.1
         networks:
             - smo-net
         ports:
             - 9990:9990
         environment:
                 smo_influxdb_host: "smo-influxdb"
                 smo_influxdb_port: "8086"
                 smo_kafka_host: "smo-kafka"
                 smo_kafka_port: "29092"
                 loglevel: "ERROR"
                 enable_assert: "False"
         depends_on:
             - smo-kafka
             - smo-influxdb
  smo-post-config:
         container_name: smo-post-config
         image: nexus3.o-ran-sc.org:10004/smo-post-config:5.0.1
         environment:
             smo_influxdb_host: "smo-influxdb"
             smo_influxdb_port: "8086"
             smo_grafana_host: "smo-grafana"
             smo_grafana_port: "3000"
             smo_grafana_auth: "admin:admin"
         depends_on:
             - smo-grafana
         networks:
             - smo-net

networks:
        smo-net:
                driver: bridge
                name: smo-net
