{
 "title": "Events Demo",
 "description": "This Dashboard provides a general overview of a host, with templating to select the hostname.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "SHOW TAG VALUES WITH KEY=system"
   }
  ]
 },
 "panels": [
  {
   "title": "host load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "system" ], "type": "tag" }
     ],
     "measurement": "measurementload",
     "query": "SELECT moving_average(\"longTerm\", 5) AS \"alias\", moving_average(\"midTerm\", 5), moving_average(\"shortTerm\", 5) FROM \"measurementload\" WHERE (\"system\" =~ /^$host$/) AND $timeFilter GROUP BY \"system\"",
     "select": [
      [
       { "params": [ "longTerm" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "Long Term" ], "type": "alias" }
      ],
      [
       { "params": [ "midTerm" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "Mid Term" ], "type": "alias" }
      ],
      [
       { "params": [ "shortTerm" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "Short Term" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "host CPU Usage User",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "cpuIdentifier" ], "type": "tag" }
     ],
     "measurement": "measurementcpuusage",
     "query": "SELECT mean(\"cpusystem\") FROM \"cpu\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "cpuUsageUser" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Received Octets",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Octets/Packets" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "nicIdentifier" ], "type": "tag" }
     ],
     "measurement": "measurementnicperformance",
     "query": "SELECT moving_average(\"receivedTotalPacketsAccumulated\", 5) FROM \"measurementnicperformance\" WHERE (\"system\" =~ /^$host$/) AND $timeFilter GROUP BY \"system\", \"nicIdentifier\"",
     "select": [
      [
       {
        "params": [
         "receivedTotalPacketsAccumulated"
        ],
        "type": "field"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transmitted Octets",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Octets/Packets" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "nicIdentifier" ], "type": "tag" }
     ],
     "measurement": "measurementnicperformance",
     "select": [
      [
       { "params": [ "receivedOctetsAccumulated" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage SDA",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "diskIdentifier" ], "type": "tag" }
     ],
     "measurement": "measurementdiskusage",
     "query": "SELECT moving_average(\"diskOpsWriteLast\", 5) FROM \"autogen\".\"diskUsage\" WHERE (\"system\" =~ /^$host$/ AND \"disk\" = 'sda') AND $timeFilter GROUP BY \"system\", \"disk\"",
     "select": [
      [
       { "params": [ "diskOpsWriteLast" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "diskIdentifier", "operator": "=", "value": "sda" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage SDB",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "system" ], "type": "tag" },
      { "params": [ "diskIdentifier" ], "type": "tag" }
     ],
     "measurement": "measurementdiskusage",
     "query": "SELECT moving_average(\"diskOpsWriteLast\", 5) FROM \"autogen\".\"measurementdiskusage\" WHERE (\"system\" =~ /^$host$/ AND \"diskIdentifier\" = 'sdb') AND $timeFilter GROUP BY \"system\", \"diskIdentifier\"",
     "select": [
      [
       { "params": [ "diskOpsWriteLast" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "diskIdentifier", "operator": "=", "value": "sdb" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "system" ], "type": "tag" }
     ],
     "measurement": "measurementmemoryusage",
     "select": [
      [
       { "params": [ "memoryCached" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "Memory Cached" ], "type": "alias" }
      ],
      [
       { "params": [ "memoryUsed" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "Memory Used" ], "type": "alias" }
      ],
      [
       { "params": [ "memoryFree" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "Memory Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Fault",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "system" ], "type": "tag" }
     ],
     "measurement": "fault",
     "query": "SELECT \"sequence\" FROM \"autogen\".\"fault\" WHERE (\"system\" =~ /^$host$/) AND $timeFilter GROUP BY \"system\"",
     "select": [
      [
       { "params": [ "sequence" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}